//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.25 at 11:54:32 AM IST 
//


package com.txodds;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for odds complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="odds">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="o1" type="{}odd"/>
 *         &lt;element name="o2" type="{}odd"/>
 *         &lt;element name="o3" type="{}odd"/>
 *         &lt;element name="o4" type="{}odd" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="i" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="time" use="required" type="{}datetime" />
 *       &lt;attribute name="starting_time" use="required" type="{}datetime_opt" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "odds", propOrder = {
    "o1",
    "o2",
    "o3",
    "o4"
})
public class Odds {

    @XmlElement(required = true)
    protected Odd o1;
    @XmlElement(required = true)
    protected Odd o2;
    @XmlElement(required = true)
    protected Odd o3;
    protected Odd o4;
    @XmlAttribute(name = "i", required = true)
    protected BigInteger i;
    @XmlAttribute(name = "time", required = true)
    protected XMLGregorianCalendar time;
    @XmlAttribute(name = "starting_time", required = true)
    protected String startingTime;

    /**
     * Gets the value of the o1 property.
     * 
     * @return
     *     possible object is
     *     {@link Odd }
     *     
     */
    public Odd getO1() {
        return o1;
    }

    /**
     * Sets the value of the o1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Odd }
     *     
     */
    public void setO1(Odd value) {
        this.o1 = value;
    }

    /**
     * Gets the value of the o2 property.
     * 
     * @return
     *     possible object is
     *     {@link Odd }
     *     
     */
    public Odd getO2() {
        return o2;
    }

    /**
     * Sets the value of the o2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Odd }
     *     
     */
    public void setO2(Odd value) {
        this.o2 = value;
    }

    /**
     * Gets the value of the o3 property.
     * 
     * @return
     *     possible object is
     *     {@link Odd }
     *     
     */
    public Odd getO3() {
        return o3;
    }

    /**
     * Sets the value of the o3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Odd }
     *     
     */
    public void setO3(Odd value) {
        this.o3 = value;
    }

    /**
     * Gets the value of the o4 property.
     * 
     * @return
     *     possible object is
     *     {@link Odd }
     *     
     */
    public Odd getO4() {
        return o4;
    }

    /**
     * Sets the value of the o4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Odd }
     *     
     */
    public void setO4(Odd value) {
        this.o4 = value;
    }

    /**
     * Gets the value of the i property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getI() {
        return i;
    }

    /**
     * Sets the value of the i property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setI(BigInteger value) {
        this.i = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime(XMLGregorianCalendar value) {
        this.time = value;
    }

    /**
     * Gets the value of the startingTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartingTime() {
        return startingTime;
    }

    /**
     * Sets the value of the startingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartingTime(String value) {
        this.startingTime = value;
    }

}
